version: 2

# Machines configs
machine_python3_redis: &machine_python3_redis
  docker:
    - image: circleci/python:3.6.6
    - image: circleci/redis:3.2-alpine


# Individual (shared) steps.
step_checkout_repo: &step_checkout_repo
  checkout


jobs:
  test:
    <<: *machine_python3_redis
    steps:
      - *step_checkout_repo
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          key: v1-deps-{{ checksum "requirements_test.txt" }}
      - run:
          name: Create virtualenv and install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements_test.txt
      - save_cache:
          key: v1-deps-{{ checksum "requirements_test.txt" }}
          paths:
            - "venv"
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            make debug_pytest
            codecov
  flake8:
    docker:
      - image: circleci/python:3.6.6
    steps:
      - *step_checkout_repo
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Run flake8
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install flake8
            flake8 . --exclude=migrations,venv

workflows:
  version: 2
  test:
    jobs:
      - test
      - flake8
